# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_inspect.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Inspect(object):
    def setupUi(self, Inspect):
        Inspect.setObjectName("Inspect")
        Inspect.resize(513, 357)
        self.verticalLayout = QtWidgets.QVBoxLayout(Inspect)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(Inspect)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.btn_add_image = QtWidgets.QPushButton(Inspect)
        self.btn_add_image.setObjectName("btn_add_image")
        self.horizontalLayout_14.addWidget(self.btn_add_image)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.wtable_album = QtWidgets.QTableWidget(Inspect)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wtable_album.sizePolicy().hasHeightForWidth())
        self.wtable_album.setSizePolicy(sizePolicy)
        self.wtable_album.setBaseSize(QtCore.QSize(0, 0))
        self.wtable_album.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wtable_album.setAutoFillBackground(False)
        self.wtable_album.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wtable_album.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.wtable_album.setObjectName("wtable_album")
        self.wtable_album.setColumnCount(3)
        self.wtable_album.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.wtable_album.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.wtable_album.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.wtable_album.setHorizontalHeaderItem(2, item)
        self.wtable_album.horizontalHeader().setVisible(False)
        self.wtable_album.horizontalHeader().setDefaultSectionSize(70)
        self.wtable_album.horizontalHeader().setHighlightSections(True)
        self.wtable_album.horizontalHeader().setMinimumSectionSize(70)
        self.wtable_album.horizontalHeader().setStretchLastSection(True)
        self.wtable_album.verticalHeader().setVisible(False)
        self.wtable_album.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.wtable_album)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_cancel = QtWidgets.QPushButton(Inspect)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_4.addWidget(self.btn_cancel)
        self.btn_done = QtWidgets.QPushButton(Inspect)
        self.btn_done.setObjectName("btn_done")
        self.horizontalLayout_4.addWidget(self.btn_done)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Inspect)
        QtCore.QMetaObject.connectSlotsByName(Inspect)

    def retranslateUi(self, Inspect):
        _translate = QtCore.QCoreApplication.translate
        Inspect.setWindowTitle(_translate("Inspect", "快速查看"))
        self.label_12.setText(_translate("Inspect", "相册"))
        self.btn_add_image.setText(_translate("Inspect", "添加"))
        item = self.wtable_album.horizontalHeaderItem(0)
        item.setText(_translate("Inspect", "新建列"))
        item = self.wtable_album.horizontalHeaderItem(1)
        item.setText(_translate("Inspect", "新建列"))
        item = self.wtable_album.horizontalHeaderItem(2)
        item.setText(_translate("Inspect", "新建列"))
        self.btn_cancel.setText(_translate("Inspect", "取消"))
        self.btn_done.setText(_translate("Inspect", "保存"))
