# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_image_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Image_Item(object):
    def setupUi(self, Image_Item):
        Image_Item.setObjectName("Image_Item")
        Image_Item.resize(342, 324)
        self.verticalLayout = QtWidgets.QVBoxLayout(Image_Item)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_image_item = QtWidgets.QLabel(Image_Item)
        self.label_image_item.setText("")
        self.label_image_item.setObjectName("label_image_item")
        self.verticalLayout.addWidget(self.label_image_item)
        self.btn_delete = QtWidgets.QPushButton(Image_Item)
        self.btn_delete.setStyleSheet("color:#ffffff;background:#7c1823")
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout.addWidget(self.btn_delete)

        self.retranslateUi(Image_Item)
        QtCore.QMetaObject.connectSlotsByName(Image_Item)

    def retranslateUi(self, Image_Item):
        _translate = QtCore.QCoreApplication.translate
        Image_Item.setWindowTitle(_translate("Image_Item", "原图"))
        self.btn_delete.setText(_translate("Image_Item", "删除"))
