# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../UI/ui_zoom.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zoom(object):
    def setupUi(self, Zoom):
        Zoom.setObjectName("Zoom")
        Zoom.resize(465, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Zoom)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Zoom)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.graphicsView = QtWidgets.QGraphicsView(Zoom)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout_2.setStretch(0, 10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox = QtWidgets.QSpinBox(Zoom)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.pushButton_3 = QtWidgets.QPushButton(Zoom)
        self.pushButton_3.setMaximumSize(QtCore.QSize(78, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.image_next_button = QtWidgets.QPushButton(Zoom)
        self.image_next_button.setObjectName("image_next_button")
        self.horizontalLayout.addWidget(self.image_next_button)
        self.pushButton_2 = QtWidgets.QPushButton(Zoom)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(Zoom)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Zoom)
        QtCore.QMetaObject.connectSlotsByName(Zoom)

    def retranslateUi(self, Zoom):
        _translate = QtCore.QCoreApplication.translate
        Zoom.setWindowTitle(_translate("Zoom", "缩放"))
        self.label.setText(_translate("Zoom", "第 3 张 / 共 7 张"))
        self.pushButton_3.setText(_translate("Zoom", "<"))
        self.image_next_button.setText(_translate("Zoom", ">"))
        self.pushButton_2.setText(_translate("Zoom", "取消"))
        self.pushButton.setText(_translate("Zoom", "确认"))
